// This component was generated by @sitecore-search/cli on Sat Mar 08 2025 15:39:57 GMT+0530 (India Standard Time)

import type { ActionProp, ItemClickedAction } from "@sitecore-search/react";
import { ArticleCard } from "@sitecore-search/ui";

type ArticleCardItemCardProps = {
  className?: string;
  displayText?: boolean;
  article: any;
  onItemClick: ActionProp<ItemClickedAction>;
  index: number;
  setActiveMarker: any;
  customArticleRenderer?: (article: any) => JSX.Element;
};

const ArticleHorizontalItemCard = ({
  article,
  setActiveMarker,
  customArticleRenderer,
}: ArticleCardItemCardProps) => {
  const renderData = () => {
    if (customArticleRenderer) {
      return <>{customArticleRenderer(article)}</>;
    }
    return (
      <div>
        <h2 className="articleTitle text-2xl font-semibold text-gray-900">
          {article.name}
        </h2>
        <p className="text-gray-600 mt-2">{article.description}</p>
        <p className="text-sm text-gray-500 block mt-1">
          Lat: {article.latitude}, Long: {article.longitude}
        </p>
        <a
          href={article?.url}
          className="mt-4 block w-fit  bg-blue-500 text-white py-2 px-4 rounded-xl hover:bg-blue-600"
        >
          Learn More
        </a>
      </div>
    );
  };
  return (
    <div
      key={article.id}
      id={`google_map_store_${article?.id}`}
      onClick={(e) => {
        e.preventDefault();
        const element = document.getElementById("google-map");
        if (element) {
          window.scrollTo({
            top: element.offsetTop,
            behavior: "smooth",
          });
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          if (setActiveMarker) setActiveMarker(article as any);
        }
      }}
      className="articleBox bg-gray-100 mb-[30px] rounded-2xl shadow-lg p-6 hover:scale-105 transition-transform duration-300"
    >
      {renderData()}
    </div>
  );
};
export default ArticleHorizontalItemCard;
