// This component was generated by @sitecore-search/cli on Sat Mar 08 2025 15:39:57 GMT+0530 (India Standard Time)

type QueryResultsSummaryProps = {
  currentPage: number;
  itemsPerPage: number;
  totalItemsReturned: number;
  totalItems: number;
};
const QueryResultsSummary = ({
  currentPage,
  itemsPerPage,
  totalItems,
  totalItemsReturned,
}: QueryResultsSummaryProps) => {
  return (
    <div className="searchResultMessage text-right w-full flex justify-end font-bold my-auto mx-0 text-black text-[20px] my-[20px]">
      Showing {itemsPerPage * (currentPage - 1) + 1} -{" "}
      {itemsPerPage * (currentPage - 1) + totalItemsReturned} of {totalItems}{" "}
      results
    </div>
  );
};

export default QueryResultsSummary;
